version: "3"
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
      - ./mosquitto/log/:/mosquitto/log/
      - ./mosquitto/data:/mosquitto/data
    networks:
      - localnet
    ports:
      - "1883:1883"
      - "9001:9001"
  classic_mqtt:
    image: classic_mqtt
    build: .
    environment:
      - LOGLEVEL=DEBUG
    depends_on:
      - mosquitto
    networks:
      - localnet

    # Note you need to create your own .env file and add all of the ${VARIABLES} used below 
    # VS Code lets you create ".env" easily, file explorer in Windows does not.
    command: "--classic ${CLASSIC_HOST} --classic_port ${CLASSIC_PORT} --mqtt mosquitto --mqtt_root ${CLASSIC_ROOT} --user ${USER_ID} --pass ${USER_PASS}"
networks:
  localnet: