version: "3"
services:
  mosquitto:
    hostname: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
      - ./mosquitto/mosquitto.passwd:/mosquitto/config/mosquitto.passwd
    networks:
      - localnet
    ports:
      - "1883:1883"
  classic_mqtt:
    image: classic_mqtt
    build: .
    environment:
      - LOGLEVEL=DEBUG
    depends_on:
      - mosquitto
    networks:
      - localnet

    # Note you need to create your own .env file in the same directory as this yml file. 
    # In it add ALL of the ${VARIABLES} used below. In windows, VS Code lets you create ".env" easily, 
    # but in file explorer you cannot. On Linux, no issue.  
    # Note, in the mosquitto.passwd file in the repo there are 2 users or you can create your own:
    # ClassicPublisher password = ClassicPub123
    # ClassicClient password= ClassicClient123
    #
    # The file should look like the following.
    #
    # CLASSIC_NAME=<Name of you Classic usually "classic">
    # CLASSIC=<IP address or URL>
    # CLASSIC_PORT=<Port usually 502>
    # MQTT_ROOT=<The MQTT Root, usually ClassicMQTT>
    # MQTT_USER=ClassicPublisher
    # MQTT_PASS=ClassicPub123
    #
    # After you have created the .env file issue the following command to build and run it:
    # docker-compose -f classic_mqtt_compose.yml up
    #
    # Note, if you change the .env file after you run this command the first time, you need to issue 
    # the following command to re-build it before running it again.
    # docker-compose -f classic_mqtt_compose.yml build
    #
    command: "--classic_name ${CLASSIC_NAME} --classic ${CLASSIC} --classic_port ${CLASSIC_PORT} --mqtt mosquitto --mqtt_root ${MQTT_ROOT} --mqtt_user ${MQTT_USER} --mqtt_pass ${MQTT_PASS}"
networks:
  localnet: